1. Generate Arithmetic Exception without exception handling:
Caught Error: division by zero

2. Handle Arithmetic Exception using try-catch block:
Handled ArithmeticException: division by zero

3. Method which throws exception and called in main without try block:
Caught Exception: This is an exception from the method!

4. Program with multiple catch blocks:
Error: Division by zero! division by zero

5. Throw exception with your own message:
Caught Exception: This is a custom exception message!

6. Create your own exception:
Caught CustomException: This is my custom exception!

7. Program with finally block:
Error: Division by zero! division by zero
This block will always execute, no matter what.

8. Program to generate Arithmetic Exception:
Caught Arithmetic Exception: division by zero

9. Program to generate FileNotFoundException:
FileNotFoundException: [Errno 2] No such file or directory: 'non_existing_file.txt'

10. Program to generate ClassNotFoundException:
ClassNotFoundException: No module named 'some_module'

11. Program to generate IOException:
IOException: [Errno 2] No such file or directory: 'non_existing_file.txt'

12. Program to generate NoSuchFieldException:
NoSuchFieldException: 'MyClass' object has no attribute 'non_existent_field'


** Process exited - Return Code: 0 **
Press Enter to exit terminal